version: '3.8'

services:
  qrgen-backend:
    image: bgtuser/qrgen-backend:latest
    container_name: qrgen-backend
    ports:
      - "5000:5000"
    restart: always

  qrgen-frontend:
    image: bgtuser/qr-pro-generator:latest
    container_name: qrgen-frontend
    ports:
      - "2040:3000"
    environment:
      - VITE_API_URL=http://qrgen-backend:5000
    restart: always
    depends_on:
      - qrgen-backend
